name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Format 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          environments: default

      - run: pixi run format-check

  graph:
    name: Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          environments: default

      - run: pixi run test-graph

  test-gpu-m1:
    name: Tests (M1)
    runs-on: [self-hosted, runner-m1]
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - run: pixi run test-gpu-b

  examples-m1:
    name: Examples (M1)
    runs-on: [self-hosted, runner-m1]
    if: github.event_name == 'pull_request'
    needs: test-gpu
    steps:
      - uses: actions/checkout@v4
      - run: pixi run examples-b

  test-gpu-4090:
    name: Tests (4090)
    runs-on: [self-hosted, runner-4090]
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - run: pixi run test-gpu-b

  examples-4090:
    name: Examples (4090)
    runs-on: [self-hosted, runner-4090]
    if: github.event_name == 'pull_request'
    needs: test-gpu-4090
    steps:
      - uses: actions/checkout@v4
      - run: pixi run examples-b
