name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          environments: default
      - run: pixi run format-check

  graph:
    name: Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          environments: default
      - run: pixi run test-graph

  test-gpu-m1:
    env:
      PIXI_CACHE_DIR: /tmp/pixi-cache-4090
    name: Tests (M1)
    runs-on: [self-hosted, runner-m1]
    if: github.event_name == 'pull_request'
    concurrency:
      group: runner-m1-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - run: pixi clean
      - run: pixi run test-gpu-b

  examples-m1:
    name: Examples (M1)
    runs-on: [self-hosted, runner-m1]
    if: github.event_name == 'pull_request'
    needs: test-gpu-m1
    concurrency:
      group: runner-m1-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - run: pixi clean
      - run: pixi run examples-b

  test-gpu-4090:
    env:
      PIXI_CACHE_DIR: /tmp/pixi-cache-m1
    name: Tests (4090)
    runs-on: [self-hosted, runner-4090]
    if: github.event_name == 'pull_request'
    concurrency:
      group: runner-4090-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - run: pixi clean
      - run: pixi run test-gpu-b

  examples-4090:
    name: Examples (4090)
    runs-on: [self-hosted, runner-4090]
    if: github.event_name == 'pull_request'
    needs: test-gpu-4090
    concurrency:
      group: runner-4090-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - run: pixi clean
      - run: pixi run examples-b
